### Sec1 post message
POST http://127.0.0.1:8081/private/message/
Content-Type: application/json

{
  "message": {"text": "hello to sec 1"},
  "id": 1
}

### Sec1 get all
GET http://127.0.0.1:8081/public/messages/

### Sec2 post message
POST http://127.0.0.1:8082/private/message/
Content-Type: application/json

{
  "message": {"text": "hello to sec 2"},
  "id": 1
}

### Sec2 get all
GET http://127.0.0.1:8082/public/messages/


### Master post message
POST http://127.0.0.1:8080/public/message/
Content-Type: application/json

{
  "message": {"text": "hello to master 1"},
  "wc": 3
}

### Master get all
GET http://127.0.0.1:8080/public/messages/